import {
	COLOR_SCHEMES,
	COLOR_SCHEME_ATTRIBUTE,
	COLOR_SCHEME_CONFIG_ATTRIBUTE,
	COLOR_SCHEME_STORAGE_KEY,
} from '../../styles/colorSchemes.js';
import type { ColorScheme } from '../../../typings/RsgTheme.js';

/**
 * Browser-side half of the colour-scheme handshake. The inline script generated by
 * src/vite/html.ts does the same before the first paint; this module keeps the page
 * in sync afterwards and is what the ThemeToggle component calls.
 */

const isColorScheme = (value: unknown): value is ColorScheme =>
	COLOR_SCHEMES.includes(value as ColorScheme);

/** The visitor’s stored choice, or null when there is none (or storage is unusable). */
export function readStoredScheme(): ColorScheme | null {
	try {
		const value = window.localStorage.getItem(COLOR_SCHEME_STORAGE_KEY);
		return isColorScheme(value) ? value : null;
	} catch {
		// Storage can throw (disabled cookies, private mode in some browsers): not fatal
		return null;
	}
}

export function storeScheme(scheme: ColorScheme): void {
	try {
		window.localStorage.setItem(COLOR_SCHEME_STORAGE_KEY, scheme);
	} catch {
		// The choice then lasts for the page view only
	}
}

/**
 * Apply a scheme to `<html>`: `light`/`dark` set the attribute the variable sheet
 * selects on, `system` removes it so the prefers-color-scheme media query decides.
 */
export function applyScheme(scheme: ColorScheme): void {
	const root = document.documentElement;
	if (scheme === 'system') {
		root.removeAttribute(COLOR_SCHEME_ATTRIBUTE);
	} else {
		root.setAttribute(COLOR_SCHEME_ATTRIBUTE, scheme);
	}
}

/** The scheme currently applied to `<html>` (`system` when no attribute is set). */
export function readAppliedScheme(): ColorScheme {
	const value = document.documentElement.getAttribute(COLOR_SCHEME_ATTRIBUTE);
	return value === 'light' || value === 'dark' ? value : 'system';
}

/**
 * The `colorScheme` config value as written into `<html>` by the inline script.
 * `system` when absent: a custom `template` function that omits the script gets a
 * working toggle, only without the flash-free first paint.
 */
export function readConfiguredScheme(): ColorScheme {
	const value = document.documentElement.getAttribute(COLOR_SCHEME_CONFIG_ATTRIBUTE);
	return isColorScheme(value) ? value : 'system';
}
