import React from 'react';
import hashSum from 'hash-sum';
import slots from 'rsg-components/slots';
import StyleGuide from 'rsg-components/StyleGuide';
import DocsAutoloader from './DocsAutoloader.js';
import getPageTitle from './getPageTitle.js';
import getRouteData from './getRouteData.js';
import processSections from './processSections.js';
import type * as Rsg from '../../typings/index.js';

/** Shape of the `virtual:rsg-styleguide` module generated by the Vite plugin. */
export interface StyleguideObject {
	sections: Rsg.Section[];
	config: Rsg.ProcessedStyleguidistConfig;
	patterns?: string[];
	welcomeScreen?: boolean;
}

/**
 * @param {object} styleguide An object exported by the virtual:rsg-styleguide module
 * @param {number} codeRevision
 * @param {Location} [loc]
 * @param {Document} [doc]
 * @param {History} [hist]
 * @return {React.ReactElement}
 */
export default function renderStyleguide(
	styleguide: StyleguideObject,
	codeRevision: number,
	loc: { hash: string; pathname: string; search: string } = window.location,
	doc: { title: string } = document,
	hist: { replaceState: (name: string, title: string, url: string) => void } = window.history
): React.ReactElement {
	const allSections = processSections(styleguide.sections, {
		useRouterLinks: styleguide.config.pagePerSection,
	});

	const { title, pagePerSection, theme, styles } = styleguide.config;
	const { sections, displayMode } = getRouteData(allSections, loc.hash, pagePerSection);

	// Update page title
	doc.title = getPageTitle(sections, title, displayMode);

	// If the current hash location was set to just `/` (e.g. when navigating back from isolated view to overview)
	// replace the URL with one without hash, to present the user with a single address of the overview screen
	if (loc.hash === '#/') {
		const url = loc.pathname + loc.search;
		hist.replaceState('', doc.title, url);
	}

	return (
		<>
			<StyleGuide
				codeRevision={codeRevision}
				// Only calculate CSS revisions in development, when hot module replacement
				// is on, to avoid stringifying the styles in production
				cssRevision={import.meta.hot ? hashSum({ theme, styles }) : '0'}
				config={styleguide.config}
				slots={slots(styleguide.config)}
				welcomeScreen={styleguide.welcomeScreen}
				patterns={styleguide.patterns}
				sections={sections}
				allSections={allSections}
				displayMode={displayMode}
				pagePerSection={pagePerSection}
			/>
			{/*
				Renders nothing. It is here, after the style guide and outside every component
				`styleguideComponents` can replace, because that is the only place from which a
				component whose renderer never loads its own documentation can still get it
				(`lazyDocs`, ADR 0019 point 5) — and “after” is what guarantees the components
				of this page have already mounted and claimed themselves.
			*/}
			<DocsAutoloader sections={sections} displayMode={displayMode} />
		</>
	);
}
