import React from 'react';
import PropTypes from 'prop-types';
import Playground from 'rsg-components/Playground';
import { useMdxPageContext } from 'rsg-components/MdxPage/MdxPageContext';

interface RsgPlaygroundProps {
	/** Ordinal of this playground on the page, 0 based, counting playgrounds only. */
	index: number;
}

/**
 * The component the MDX loader puts in place of every playground fence.
 *
 * It renders the same `<Playground>` the `.md` path renders from `Examples.tsx`, with the same
 * props, so `exampleMode`, `settings.showcode/noeditor/padded/props`, the editor slot, the
 * isolate button, `previewDelay` and `codeRevision` all behave exactly as they do for `.md`.
 */
const RsgPlayground: React.FunctionComponent<RsgPlaygroundProps> = ({ index }) => {
	const { examples, name, exampleMode, indexOffset = 0 } = useMdxPageContext();
	const example = examples[index];
	if (!example) {
		// Only reachable if a page is rendered with examples that do not match its compiled
		// content (a stale hot update, a hand-written <RsgPlayground/>). Throwing puts the
		// message in this page’s error boundary instead of rendering an empty playground.
		throw new Error(
			`Styleguidist: this MDX page has no example ${index}. <RsgPlayground/> is generated by ` +
				`Styleguidist for each code fence; don’t write it by hand.`
		);
	}
	return (
		<Playground
			code={example.content}
			lang={example.lang}
			evalInContext={example.evalInContext}
			name={name}
			// `index` is this page’s own ordinal; the isolate link needs the component’s
			// number, which starts above zero when the page is not its only examples file
			index={indexOffset + index}
			settings={example.settings ?? {}}
			exampleMode={exampleMode}
		/>
	);
};

RsgPlayground.propTypes = {
	index: PropTypes.number.isRequired,
};

export default RsgPlayground;
