import './styles/index.js';
// `rsg-react-root` is aliased by the Vite config to the createRoot() (React 18+) or the
// ReactDOM.render() (React 16.14 and 17) implementation, see utils/reactRoot.ts
import { mountRoot } from 'rsg-react-root';
import type { StyleguideRoot } from './utils/reactRoot.js';
// The style guide data (sections, components, examples and the client part of the
// config) is generated by the Styleguidist Vite plugin (src/vite/plugin.ts)
import styleguide from 'virtual:rsg-styleguide';
import renderStyleguide from './utils/renderStyleguide.js';
import type { StyleguideObject } from './utils/renderStyleguide.js';
import createDeepLinkScroller from './utils/deepLinks.js';
import { refreshLoadedDocs, subscribeToTree } from './utils/componentDocs.js';

// Examples code revision to rerender only code examples (not the whole page) when code changes
let codeRevision = 0;

// The latest style guide data; replaced on hot updates
let currentStyleguide: StyleguideObject = styleguide;

/**
 * Fragments of the address, honoured on a cold load and on every `hashchange`.
 *
 * A cold load fires no `hashchange` event, so pasting, bookmarking or sharing a
 * `#!/Button?id=sizes` link — the shape every “on this page” entry has (ADR 0016) and the
 * one the sidebar produces at `sectionDepth: 0` — landed at the top of the page, because
 * that fragment is a route and matches no element id, so the browser’s own fragment
 * scrolling had nothing to do either. See utils/deepLinks.ts for what happens after that
 * on a page whose documentation is still arriving.
 */
const deepLinks = createDeepLinkScroller({ getSections: () => currentStyleguide.sections });

let reactRoot: StyleguideRoot | null = null;

const render = () => {
	if (!reactRoot) {
		const rootNode = document.getElementById(currentStyleguide.config.mountPointId);
		if (rootNode) {
			reactRoot = mountRoot(rootNode);
		}
	}

	if (reactRoot) {
		reactRoot.render(renderStyleguide(currentStyleguide, codeRevision));
	}
};

window.addEventListener('hashchange', render);
window.addEventListener('hashchange', () => deepLinks.onHashChange());

// On-demand documentation (`lazyDocs`, ADR 0019) is merged into the section tree while it
// is being processed, so the guide is re-rendered when a loaded answer would change the
// tree itself — the store coalesces those into one re-render per frame, and a component
// that only fills in its own body never asks for one (see utils/componentDocs.ts).
subscribeToTree(() => render());

/* istanbul ignore if */
if (import.meta.hot) {
	// Re-render when components, examples, theme or styles change (see the
	// `hotUpdate` hook of the plugin for what invalidates this module)
	import.meta.hot.accept('virtual:rsg-styleguide', (updated) => {
		if (updated) {
			currentStyleguide = updated.default;
			codeRevision += 1;
			// The loaders in the new module point at the new modules; whatever documentation
			// is already on the page is re-imported through them, so an edited component or
			// Readme updates the page with `lazyDocs` on exactly as it does without it
			refreshLoadedDocs(currentStyleguide.sections);
			render();
		}
	});
}

render();
deepLinks.onLoad();
