import './styles/index.js';
import { createRoot, Root } from 'react-dom/client';
// The style guide data (sections, components, examples and the client part of the
// config) is generated by the Styleguidist Vite plugin (src/vite/plugin.ts)
import styleguide from 'virtual:rsg-styleguide';
import renderStyleguide from './utils/renderStyleguide.js';
import type { StyleguideObject } from './utils/renderStyleguide.js';
import { getParameterByName, hasInHash, getHash } from './utils/handleHash.js';

// Examples code revision to rerender only code examples (not the whole page) when code changes
let codeRevision = 0;

// The latest style guide data; replaced on hot updates
let currentStyleguide: StyleguideObject = styleguide;

// Scrolls to origin when current window location hash points to an isolated view.
const scrollToOrigin = () => {
	const hash = window.location.hash;
	let idHashParam;

	if (hasInHash(hash, '#/') || hasInHash(hash, '#!/')) {
		// Extracts the id param of hash
		idHashParam = getParameterByName(hash, 'id');
	} else {
		idHashParam = getHash(hash, '#');
	}

	if (hash) {
		if (idHashParam) {
			const idElement = document.getElementById(idHashParam);

			if (idElement) {
				idElement.scrollIntoView(true);
			}
		} else {
			window.scrollTo(0, 0);
		}
	}
};

let reactRoot: Root | null = null;

const render = () => {
	if (!reactRoot) {
		const rootNode = document.getElementById(currentStyleguide.config.mountPointId);
		if (rootNode) {
			reactRoot = createRoot(rootNode);
		}
	}

	if (reactRoot) {
		reactRoot.render(renderStyleguide(currentStyleguide, codeRevision));
	}
};

window.addEventListener('hashchange', render);
window.addEventListener('hashchange', scrollToOrigin);

/* istanbul ignore if */
if (import.meta.hot) {
	// Re-render when components, examples, theme or styles change (see the
	// `hotUpdate` hook of the plugin for what invalidates this module)
	import.meta.hot.accept('virtual:rsg-styleguide', (updated) => {
		if (updated) {
			currentStyleguide = updated.default;
			codeRevision += 1;
			render();
		}
	});
}

render();
