// Type declarations for the virtual modules generated by the Styleguidist Vite plugin
// (see src/vite/plugin.ts and src/vite/ids.ts).

declare module 'virtual:rsg-styleguide' {
	import type { StyleguideObject } from './utils/renderStyleguide.js';

	const styleguide: StyleguideObject;
	export default styleguide;
}
